/**
 * Loading gameScreen for loading all assets before starting the game
 *
 * @constructor
 */
function LoadingScreen() {

    this.images = [
        'abilityAngelic Assault',
        'abilityArrow',
        'abilityArtillery',
        'abilityAura Blast',
        'abilityBlink',
        'abilityCannon',
        'abilityCritical Blast',
        'abilityDecimation',
        'abilityFire',
        'abilityGyro Slash',
        'abilityIonic Thunder',
        'abilityKO Cannon',
        'abilityLaser',
        'abilityLaser Bomb',
        'abilityLock Down',
        'abilityMissile',
        'abilityMissile Barrage',
        'abilityOverdrive',
        'abilityPerfect Shield',
        'abilityPiercing Arrow',
        'abilityPlus',
        'abilityReflect',
        'abilityReflector',
        'abilityRepulsar',
        'abilityShell',
        'abilityStasis',
        'abilitySweeping Blade',
        'abilitySword',
        'abilityTargeter',
        'abilityWave Burst',
        'AngelBar',
        'AngelMovementSpeedUI',
        'AngelMovementSpeedUISelected',
        'AngelPowerAuraUI',
        'AngelPowerAuraUISelected',
        'AngelPrismBeamPowerUI',
        'AngelPrismBeamPowerUISelected',
        'AngelShieldRechargeUI',
        'AngelShieldRechargeUISelected',
        'AngelStaticAuraUI',
        'AngelStaticAuraUISelected',
        'arrow',
        'BetaBar',
        'BetaChargeSpeedUI',
        'BetaChargeSpeedUISelected',
        'BetaMovementSpeedUI',
        'BetaMovementSpeedUISelected',
        'BetaShieldRechargeUI',
        'BetaShieldRechargeUISelected',
        'BetaShurikenPierceUI',
        'BetaShurikenPierceUISelected',
        'BetaStealthDurationUI',
        'BetaStealthDurationUISelected',
        'BlitzBar',
        'BlitzCooldownReductionUI',
        'BlitzCooldownReductionUISelected',
        'BlitzMovementSpeedUI',
        'BlitzMovementSpeedUISelected',
        'BlitzShieldRechargeUI',
        'BlitzShieldRechargeUISelected',
        'BlitzShotgunProjectilesUI',
        'BlitzShotgunProjectilesUISelected',
        'BlitzSlowingDurationUI',
        'BlitzSlowingDurationUISelected',
        'bossDragonEnd',
        'bossDragonGun',
        'bossDragonHead',
        'bossDragonLeftWing',
        'bossDragonRightWing',
        'bossDragonSegment',
        'bossDragonTurret',
        'bossFire',
        'bossFireClawLeft',
        'bossFireClawRight',
        'bossFireEnd',
        'bossFireSegment',
        'bossFlame',
        'bossHeavy',
        'bossHeavyCoverLeft',
        'bossHeavyCoverRight',
        'bossLaser',
        'bossMine',
        'bossPunch',
        'bossQueen',
        'bossQueenAbdomen',
        'bossQueenWingLeft',
        'bossQueenWingRight',
        'bullet',
        'buttonClampBottom',
        'buttonClampBR',
        'buttonClampTop',
        'buttonClampTR',
        'CommandoBar',
        'CommandoDroneRangeUI',
        'CommandoDroneRangeUISelected',
        'CommandoDroneShotsUI',
        'CommandoDroneShotsUISelected',
        'CommandoLMGBaseDamageUI',
        'CommandoLMGBaseDamageUISelected',
        'CommandoMovementSpeedUI',
        'CommandoMovementSpeedUISelected',
        'CommandoShieldRechargeUI',
        'CommandoShieldRechargeUISelected',
        'controlsScreen',
        'cursor',
        'damage',
        'drone',
        'droneArmLeft',
        'droneArmRight',
        'droneAssaulter',
        'droneGun',
        'droneHealer',
        'dronePropeller',
        'droneShielder',
        'EmptyBar',
        'enemyHeavyArtillery',
        'enemyHeavyBomber',
        'enemyHeavyGrabber',
        'enemyHeavyGrabberArm',
        'enemyHeavyGrabberArmLeft',
        'enemyHeavyGrabberArmRight',
        'enemyHeavyMedic',
        'enemyHeavyMelee',
        'enemyHeavyOrbiter',
        'enemyHeavyOrbiterTail',
        'enemyHeavyRanged',
        'enemyHeavySpinner',
        'enemyHeavySpinnerBack',
        'enemyHiveDefender',
        'enemyHiveDefenderAbdomen',
        'enemyHiveDefenderWingLeft',
        'enemyHiveDefenderWingRight',
        'enemyHiveDrone',
        'enemyHiveDroneAbdomen',
        'enemyHiveDroneWingLeft',
        'enemyHiveDroneWingRight',
        'enemyHunter',
        'enemyHunterEnd',
        'enemyHunterSegment',
        'enemyLightArtillery',
        'enemyLightBomber',
        'enemyLightGrabber',
        'enemyLightGrabberArm',
        'enemyLightMedic',
        'enemyLightMelee',
        'enemyLightOrbiter',
        'enemyLightOrbiterTail',
        'enemyLightRanged',
        'enemyLightSpinner',
        'enemyLightSpinnerBack',
        'enemyPaladin',
        'enemyPointer',
        'enemyRailer',
        'enemySnatcher',
        'enemySnatcherArm',
        'enemySnatcherArmLeft',
        'enemySnatcherArmRight',
        'enemySolar',
        'enemySolarBack',
        'enemyTurret',
        'EX1',
        'EX10',
        'EX2',
        'EX3',
        'EX4',
        'EX5',
        'EX6',
        'EX7',
        'EX8',
        'EX9',
        'exp1',
        'exp25',
        'exp5',
        'explodeBaseCommando',
        'explodeBaseEnemy',
        'explodeBaseGuardian',
        'explodeBaseValkyrie',
        'explodeBitCommando',
        'explodeBitEnemy',
        'explodeBitGuardian',
        'explodeBitValkyrie',
        'explodeSmoke1',
        'explodeSmoke2',
        'explodeSmoke3',
        'explodeSmoke4',
        'fire',
        'fistLeft',
        'fistRight',
        'FullBar',
        'grappleHook',
        'GuardianBar',
        'GuardianBlastRadiusUI',
        'GuardianBlastRadiusUISelected',
        'GuardianKnockbackUI',
        'GuardianKnockbackUISelected',
        'GuardianMinigunAttackSpeedUI',
        'GuardianMinigunAttackSpeedUISelected',
        'GuardianMovementSpeedUI',
        'GuardianMovementSpeedUISelected',
        'GuardianShieldRechargeUI',
        'GuardianShieldRechargeUISelected',
        'hammer',
        'healingPad',
        'healthBarSymbol',
        'HeavyBomberMine',
        'KnightArrowVolleyCountUI',
        'KnightArrowVolleyCountUISelected',
        'KnightBar',
        'KnightGrappleStunUI',
        'KnightGrappleStunUISelected',
        'KnightMovementSpeedUI',
        'KnightMovementSpeedUISelected',
        'KnightShieldRechargeUI',
        'KnightShieldRechargeUISelected',
        'KnightSwordLifeStealUI',
        'KnightSwordLifeStealUISelected',
        'KnightSwordSwingArcUI',
        'KnightSwordSwingArcUISelected',
        'laser',
        'LevelUpWords',
        'LightBomberMine',
        'lmgBullet',
        'minigunBullet',
        'missile',
        'pAngel',
        'pAngelAbilityWingLeft',
        'pAngelAbilityWingRight',
        'pAngelBody',
        'pAngelHealingKit',
        'pAngelPrismBeam',
        'pAngelShield',
        'pBeta',
        'pBetaBlade',
        'pBetaBladeCharge',
        'pBetaBody',
        'pBetaShield',
        'pCommando',
        'pCommandoBody',
        'pCommandoChargeBall',
        'pCommandoChargeLaser',
        'pCommandoDroneKit',
        'pCommandoLMG',
        'pCommandoShield',
        'pCommandoTarget',
        'pDefense',
        'pDefenseBody',
        'pDefenseGun',
        'pDefenseMissile',
        'pDefenseShield',
        'perfectShield',
        'PEX1',
        'PEX10',
        'PEX2',
        'PEX3',
        'PEX4',
        'PEX5',
        'PEX6',
        'PEX7',
        'PEX8',
        'PEX9',
        'pKnight',
        'pKnightArm',
        'pKnightBody',
        'pKnightGrappleEmpty',
        'pKnightGrappleFull',
        'pKnightQuiver',
        'pKnightShield',
        'pPower',
        'pPowerBody',
        'pPowerFlame',
        'pPowerLaser',
        'pPowerShield',
        'pPowerSpread',
        'pSpeed',
        'pSpeedBody',
        'pSpeedGun',
        'pSpeedShield',
        'pSpeedShotgun',
        'pTraitorBody',
        'pTraitorFlame',
        'pTraitorLaser',
        'pTraitorShield',
        'pTraitorSpread',
        'pValkyrie',
        'pValkyrieBody',
        'pValkyrieGun',
        'pValkyrieRailLeft',
        'pValkyrieRailRight',
        'pValkyrieRod',
        'pValkyrieScope',
        'pValkyrieShell',
        'pValkyrieShield',
        'pValkyrieTarget',
        'pValkyrieTurret',
        'pValkyrieWing',
        'rocket',
        'shell',
        'SlayerAttackSpeedUI',
        'SlayerAttackSpeedUISelected',
        'SlayerBar',
        'SlayerFlamethrowerRangeUI',
        'SlayerFlamethrowerRangeUISelected',
        'SlayerLaserSpreadUI',
        'SlayerLaserSpreadUISelected',
        'SlayerMovementSpeedUI',
        'SlayerMovementSpeedUISelected',
        'SlayerShieldRechargeUI',
        'SlayerShieldRechargeUISelected',
        'slowMissile',
        'statAbsorbed',
        'statBoss',
        'statDealt',
        'statDeaths',
        'statDragon',
        'statExp',
        'statGames',
        'statHeavy',
        'statKills',
        'statLevel',
        'statLight',
        'statMiniboss',
        'statRescues',
        'statScore',
        'statTaken',
        'stinger',
        'sword',
        'targeterMissile',
        'tile',
        'turretBase',
        'turretGun',
        'uiArrowLeft',
        'uiArrowRight',
        'upgradeArrow',
        'upgradeCharge',
        'upgradeChargeSpeed',
        'upgradeCooldown',
        'upgradeDamage',
        'upgradeDroneRange',
        'upgradeDroneShots',
        'upgradeDual',
        'upgradeExplosion',
        'upgradeFlamethrower',
        'upgradeGrapple',
        'upgradeHealth',
        'upgradeKnockback',
        'upgradeLaser',
        'upgradeLifesteal',
        'upgradeLMGDamage',
        'upgradeMinigun',
        'upgradeRange',
        'upgradeShield',
        'upgradeShotgun',
        'upgradeShurikenPierce',
        'upgradeSlash',
        'upgradeSlow',
        'upgradeSpeed',
        'upgradeSpread',
        'upgradeStealthDuration',
        'ValkyrieBar',
        'ValkyrieChargeSpeedUI',
        'ValkyrieChargeSpeedUISelected',
        'ValkyrieDualShotUI',
        'ValkyrieDualShotUISelected',
        'ValkyrieMovementSpeedUI',
        'ValkyrieMovementSpeedUISelected',
        'ValkyrieRailGunRangeUI',
        'ValkyrieRailGunRangeUISelected',
        'ValkyrieShieldRechargeUI',
        'ValkyrieShieldRechargeUISelected'
    ];
    this.index = 0;
    this.loading = false;
}

/**
 * Counts images as they are loaded
 */
LoadingScreen.prototype.imageLoaded = function() {
    gameScreen.index++;
};

/**
 * Updates the loading screen, transitioning when needed
 */ 
LoadingScreen.prototype.update = function() {

    // Start loading the images
    if (!this.loading) {
        this.loading = true;
        for (var i = 0; i < this.images.length; i++) {
            images.get(this.images[i], this.imageLoaded);
        }
    }

    // Finished loading
    else if (this.index == this.images.length) {
        gameScreen = new TitleScreen();
    }
};

/**
 * Draws the loading gameScreen
 */
LoadingScreen.prototype.draw = function() {

    var cx = controls.mouse.x;
    var cy = controls.mouse.y;

    var wx = camera.canvas.width / 2;
    var wy = camera.canvas.height / 2;

    // Draw the background
    ui.drawBackground();

    camera.ctx.font = '50px Flipbash';
    camera.ctx.fillStyle = '#FFFFFF';
    var text = Math.round(100 * this.index / this.images.length) + '%';
    camera.ctx.fillText(text, wx - camera.ctx.measureText(text).width / 2, wy);

    // Draw the cursor
    ui.drawCursor();
};
